/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phuket_tour_decoder_Mp3Decoder */

#ifndef _Included_com_phuket_tour_decoder_Mp3Decoder
#define _Included_com_phuket_tour_decoder_Mp3Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phuket_tour_decoder_Mp3Decoder
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_phuket_tour_decoder_Mp3Decoder_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_phuket_tour_decoder_Mp3Decoder
 * Method:    decode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_decoder_Mp3Decoder_decode
  (JNIEnv *, jobject);

/*
 * Class:     com_phuket_tour_decoder_Mp3Decoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_decoder_Mp3Decoder_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
